# Generated by Django 4.0.4 on 2022-06-18 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customer_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='company',
            new_name='customer',
        ),
    ]
